#! /bin/sh

pkill pulseaudio
pulseaudio --start
xset r rate 200 100
xrdb .Xresources
setxkbmap -option ctrl:nocaps

pkill -USR1 -x sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false 
bspc config gapless_monocle      false 

bspc config normal_border_color "#817c9c"
bspc config focused_border_color "#9ccfd8"
